### ISSUE TITLE
Default input parameter values are not correctly set in Nextflow schema JSON file

### ISSUE THREAD

**Issue by tverbeiren** [viash-hub/demultiplex#42]
This is in the Viash config of the `runner`:

```yaml
  - name: Output arguments
    arguments:
      - name: --fastq_output
        type: file
        direction: output
        default: "fastq"
      - name: --falco_output
        type: file
        direction: output
        default: "qc/fastqc"
      - name: --multiqc_output
        type: file
        direction: output
        default: "qc/multiqc_report.html"
```

When rendering the schema file, it becomes:

<img width="802" alt="Image" src="https://github.com/user-attachments/assets/b3c88c34-298c-4775-8e6f-2980cbc5f767" />

Somehow, the information about the default value is not taken into account.
